### ISSUE TITLE
create Service failed under a NAT VPC subnet

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#13]
Create Service with YAML fail:
```
kind: Service
apiVersion: v1
metadata:
  name: xx
  namespace: default
spec:
  selector:
    app: xx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
```

Error message is:
```
Error creating load balancer (will retry): Failed to ensure load balancer for service default/xx: Error Message: "Subnet information error.", Error Code: "SubnetInvalid", Status Code: 403, Request Id: "xxxx"
```

My subnet type is NAT.
